# Alpine-based Autopilot Pattern implementation
# http://autopilotpattern.io/

prometheus:
  image: prom/prometheus:0.17.0
    labels:
      - triton.cns.services=prometheus
    mem_limit: 128m
    restart: always
    env_file: _env
    command: >
      /bin/containerpilot
      -config file:///usr/local/etc/containerpilot/containerpilot.json
      /bin/sh
